# Github action to build Docker image (testing-tag) from dev branch

name: Docker build dev

on:
  push:
    branches:
      - dev
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: 'buanet/docker.watchdog'
          ref: 'beta'
        
      - name: Get versions
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-2 | sed -r 's#^(.{0})#\1latest-#')"
          echo "This is the Version: $VERSION"
          echo "This is the Major Version: $MAJORVERSION"

      - name: Set up manifest tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
          chmod +x manifest-tool

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image (amd64)
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./amd64
          file: ./amd64/Dockerfile
          push: true
          platforms: linux/amd64
          tags: buanet/watchdog:testing
          
      - name: Build Docker image (armv7)
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./arm32v7
          file: ./arm32v7/Dockerfile
          push: false
          platforms: linux/arm/v7
          tags: buanet/watchdog:testing
          
