# Github action to build Docker image (testing-tag) from dev branch

name: Docker build dev

on:
  push:
    branches:
      - dev
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: 'buanet/docker.watchdog'
          ref: 'beta'
        
      - name: Testing
        run: |
          echo "Some testing..."
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-2 | sed -r 's#^(.{0})#\1latest-#')"
          echo "This is the Version: $VERSION"
          echo "This is the Major Version: $MAJORVERSION"

      - name: Setup Manifest Tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
          chmod +x manifest-tool



#      - name: Docker Setup Buildx
#        uses: docker/setup-buildx-action@v1.3.0

#      - name: Docker Login
#        uses: docker/login-action@v1.10.0
#        with:
#          username: ${{ secrets.DOCKER_USER }}
#          password: ${{ secrets.DOCKER_PASS }}

#      - name: Build and push Docker images
#        uses: docker/build-push-action@v2.5.0
#        with:
#          context: ./amd64/
#          file: ./Dockerfile
