# Github action to build Docker image from dev branch (tag: testing)

name: Build Docker image from dev branch

on:
  push:
    branches:
      - dev
      
jobs:
  bulid_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (dev)
        uses: actions/checkout@v2.3.4
        with:
          repository: 'buanet/docker.watchdog'
          ref: 'dev'
        
      - name: Get versions
        run: |
          VERSION="$(cat .VERSION)"
          MAJORVERSION="$(cat .VERSION | cut -c 1-2 | sed -r 's#^(.{0})#\1latest-#')"
          echo "This is the Version: $VERSION"
          echo "This is the Major Version: $MAJORVERSION"

      - name: Set up manifest tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v0.7.0/manifest-tool-linux-amd64 -O manifest-tool
          chmod +x manifest-tool

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

 #     - name: Login to DockerHub
 #       uses: docker/login-action@v1.10.0
 #       with:
 #         username: ${{ secrets.DOCKER_USER }}
 #         password: ${{ secrets.DOCKER_PASS }}
          
      - name: Login to GithubRegistry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_PASS }}

      - name: Build Docker image (amd64)
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./amd64
          file: ./amd64/Dockerfile
          push: true
          load: false
          platforms: linux/amd64
          tags: ghcr.io/buanet/watchdog:testing-amd64
          
      - name: Build Docker image (armv32v7)
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./arm32v7
          file: ./arm32v7/Dockerfile
          push: true
          load: false
          platforms: linux/arm/v7
          tags: ghcr.io/buanet/watchdog:testing-arm32v7
      
      - name: Build Docker image (arm64v8)
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./arm64v8
          file: ./arm64v8/Dockerfile
          push: true
          load: false
          platforms: linux/arm64
          tags: ghcr.io/buanet/watchdog:testing-arm64v8
          
      - name: Manifests
        run: |
          ls -al
          cat ./manifest_test.yml | sed "s/\$VERSION/testing/g" > manifest_temp.yaml
          cat ./manifest_temp.yaml | sed "s/\$DOCKERTAG/testing/g" > manifest_testing.yaml
          ./manifest-tool --username ${{ secrets.PACKAGES_USER }} --password ${{ secrets.PACKAGES_PASS }} push from-spec manifest_testing.yaml
          
      - name: Log
        run: docker images
  
