name: Build Docker image from dev branch

on:
  push:
    branches:
      - dev
      
jobs:
  bulid_dev:
    runs-on: ubuntu-latest
    steps:   
      - name: Delete untagged images from GitHub packages
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PACKAGES_PASS }}
          script: |
            const response = await github.request("GET /users/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: buanet
          PACKAGE_NAME: watchdog
          PER_PAGE: 100
          
